In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3],[4,5,6]])
arr3 = np.array((7,8,9))

print("Basic Array:")
print("1D Array from list:\n", arr1)
print("2D Array from list:\n" , arr2)
print("1D Array from tuple:\n", arr3)

Basic Array:
1D Array from list:
 [1 2 3 4 5]
2D Array from list:
 [[1 2 3]
 [4 5 6]]
1D Array from tuple:
 [7 8 9]


In [ ]:
# Special Arrays

zeros = np.zeros((2,3))
ones = np.ones((3,2))
identity = np.eye(5)
arange = np.arange(1,10,2)

print("Zeros Array:\n", zeros)
print("Ones Array:\n", ones)
print("Identity Array:\n", identity)
print("Arange Array:\n", arange)

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Identity Array:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Arange Array:
 [1 3 5 7 9]


In [ ]:
empty = np.empty((2,2))
full = np.full((2,2), 5)

print("Empty Array:\n", empty)
print("Full Array:\n", full)

Empty Array:
 [[1. 0.]
 [0. 1.]]
Full Array:
 [[5 5]
 [5 5]]


In [ ]:
# Creating arrays with range
# arange: Use when you know the step/gap between two consective numbers
# linespace: Use when you know the number of elements, not the step/gap

range_arange = np.arange(0,10,2)
range_linespace = np.linspace(0,10,4)

print("Arange Array:\n", range_arange)
print("Linespace Array:\n", range_linespace)

Arange Array:
 [0 2 4 6 8]
Linespace Array:
 [ 0.          3.33333333  6.66666667 10.        ]


In [ ]:
# Random Array

rand = np.random.rand(2,3)
rand_int = np.random.randint(1,10,size=(2,3))
rand_normal = np.random.randn(2,3)
rand_custom_normal = np.random.normal(5, 2, size=(2,3))
#rand_custom_normal = np.random.normal(loc=5, scale=2, size=(2,3))

print("Random Array:\n", rand)
print("Random Integer Array:\n", rand_int)
print("Random Normal Array:\n", rand_normal)
print("Random Custom Normal Array:\n", rand_custom_normal)

Random Array:
 [[0.97192465 0.33330311 0.87410759]
 [0.59355953 0.83714729 0.74342671]]
Random Integer Array:
 [[5 2 7]
 [1 4 2]]
Random Normal Array:
 [[-0.36033494 -0.19289048 -1.70132772]
 [-1.45457499 -0.48498502  0.17962223]]
Random Custom Normal Array:
 [[2.28066252 3.3395937  6.74529064]
 [5.27515517 6.98100268 5.47197186]]


In [ ]:
# Reshaping and initializing shapes
reshape = np.arange(12).reshape(3,4)
init_like = np.zeros_like(reshape)

print("Reshaped Array:\n", reshape)
print("Initialized Array:\n", init_like)

Reshaped Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Initialized Array:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


** numpy indexing and selection**

In [ ]:
arr = np.arange(0,11)
print("Initial array:\n", arr)

Initial array:
 [ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:
# get value at index
print("Value at index 5:", arr[5])

Value at index 5: 5


In [ ]:
# Get value in range
print("Value in range 1-5:", arr[1:5])

Value in range 1-5: [1 2 3 4]


Broadcasting

In [ ]:
# Setting values with index range
arr[0:5] = 100
print("Broadcasted array:\n", arr)

Broadcasted array:
 [100 100 100 100 100   5   6   7   8   9  10]


In [ ]:
# Reset array
arr = np.arange(0,11)
print("Initial array:\n", arr)

Initial array:
 [ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:
# Important note on slices
slice_of_arr = arr[0:6]
print("Slice of array:\n", slice_of_arr)

Slice of array:
 [0 1 2 3 4 5]


In [ ]:
# Change slice
slice_of_arr[:] = 99
print("Broadcasted slice of array:\n", slice_of_arr)
print("Original array:\n", arr)

Broadcasted slice of array:
 [99 99 99 99 99 99]
Original array:
 [99 99 99 99 99 99  6  7  8  9 10]


In [ ]:
# To get a copy
arr_copy = arr.copy()
print("Copied array:\n", arr_copy)
arr_copy[:] = 20
print("Copied array After change:\n", arr_copy)
print("Original array:\n", arr)

Copied array:
 [99 99 99 99 99 99  6  7  8  9 10]
Copied array After change:
 [20 20 20 20 20 20 20 20 20 20 20]
Original array:
 [99 99 99 99 99 99  6  7  8  9 10]


2D arrays

In [ ]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
print("2D array:\n", arr_2d)

2D array:
 [[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [ ]:
print("Second row of 2d array: ", arr_2d[1])
print("Second row of 2d array: ", arr_2d[1, :])

Second row of 2d array:  [20 25 30]
Second row of 2d array:  [20 25 30]


In [ ]:
# Getting individual element value
print("Individual element value at [1][0]:", arr_2d[1][0])
print("Individual element value at [1, 0] (Alternative syntax):", arr_2d[1, 0])

Individual element value at [1][0]: 20
Individual element value at [1, 0] (Alternative syntax): 20


In [ ]:
# 2d Slicing
print("2d Slicing:\n", arr_2d[:2,1:])

2d Slicing:
 [[10 15]
 [25 30]]


# Conditional Selection

In [ ]:
arr = np.arange(1,11)
print("Initial array:\n", arr)

Initial array:
 [ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# Check condition
print(arr)
print("Condition check arr > 4:\n", arr > 4)

[ 1  2  3  4  5  6  7  8  9 10]
Condition check arr > 4:
 [False False False False  True  True  True  True  True  True]


In [ ]:
# Store boolean array in different array
bool_arr = arr > 4
print("Boolean array:\n", bool_arr)

Boolean array:
 [False False False False  True  True  True  True  True  True]


In [ ]:
# Select element where condition is True
print("Select element where condition is True:\n", arr[bool_arr])

Select element where condition is True:
 [ 5  6  7  8  9 10]


In [ ]:
# Using condition directly in selection
print("Select element where condition is True:\n", arr[arr > 4])

Select element where condition is True:
 [ 5  6  7  8  9 10]


In [ ]:
# Using a variable for condition
x=2
print("Select element where condition arr > x is True:\n", arr[arr > x])

Select element where condition arr > x is True:
 [ 3  4  5  6  7  8  9 10]


# Statistical properties of numpy arrays

In [ ]:
# creating a simple array
arr = np.arange(0,10)
print("Initial array:\n", arr)

Initial array:
 [0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Shape of array
print("Shape of array:\n", arr.shape)

Shape of array:
 (10,)


In [ ]:
# Summary statistics
print("Sum of element:", np.sum(arr), "Alternative: ", arr.sum())
print("Mean of array:", np.mean(arr), "Alternative: ", arr.mean())
print("Minimum of array:", np.min(arr), "Alternative: ", arr.min())
print("Maximum of array:", np.max(arr), "Alternative: ", arr.max())
print("Standard Deviation of array:", np.std(arr), "Alternative: ", arr.std())
print("Variance of array:", np.var(arr), "Alternative: ", arr.var())
print("Median of array:", np.median(arr), "Alternative: ", np.percentile(arr, 50))

Sum of element: 45 Alternative:  45
Mean of array: 4.5 Alternative:  4.5
Minimum of array: 0 Alternative:  0
Maximum of array: 9 Alternative:  9
Standard Deviation of array: 2.8722813232690143 Alternative:  2.8722813232690143
Variance of array: 8.25 Alternative:  8.25
Median of array: 4.5 Alternative:  4.5
