In [ ]:
import numpy as np
import pandas as pd

In [ ]:
np.random.seed(101)  #Set seed for reproducivility
mydata = np.random.randint(0,101,(4,3)) #Generate random integers in the range (0,100)
print("Generate DataFrame (myData) : \n",mydata)

Generate DataFrame (myData) : 
 [[95 11 81]
 [70 63 87]
 [75  9 77]
 [40  4 63]]


In [ ]:
myindex = ['CA', 'NY', 'AZ', 'TX']
mycolumns = ['Jan', 'Feb', 'Mar']


In [ ]:
# Creating a DataFrame without index and columns
df = pd.DataFrame(data=mydata)
print("DataFrame without index and columns:\n", df)

DataFrame without index and columns:
     0   1   2
0  95  11  81
1  70  63  87
2  75   9  77
3  40   4  63


In [ ]:
# Creating DataFrame with custom index
df = pd.DataFrame(data=mydata, index=myindex)
print("DataFrame with custom index:\n", df)

DataFrame with custom index:
      0   1   2
CA  95  11  81
NY  70  63  87
AZ  75   9  77
TX  40   4  63


In [ ]:
# Creating DataFrame with custom index and custom column names
df = pd.DataFrame(data=mydata, index=myindex, columns=mycolumns)
print("DataFrame with custom index and column names:\n", df)


DataFrame with custom index and column names:
     Jan  Feb  Mar
CA   95   11   81
NY   70   63   87
AZ   75    9   77
TX   40    4   63


In [ ]:
# Displaying information about dataFrame
print("DataFrame information:\n", df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, CA to TX
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Jan     4 non-null      int64
 1   Feb     4 non-null      int64
 2   Mar     4 non-null      int64
dtypes: int64(3)
memory usage: 128.0+ bytes
DataFrame information:
 None


In [ ]:
# Create a DataFrame from a CSV file
df = pd.read_csv('tips.csv')
print("DataFrame from CSV file:\n", df)

DataFrame from CSV file:
      total_bill   tip  gender smoker   day    time  size  price_per_person  \
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49   
1         10.34  1.66    Male     No   Sun  Dinner     3              3.45   
2         21.01  3.50    Male     No   Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No   Sun  Dinner     2             11.84   
4         24.59  3.61  Female     No   Sun  Dinner     4              6.15   
..          ...   ...     ...    ...   ...     ...   ...               ...   
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

             Payer Name     CC Number

In [ ]:
print("Columns are:\n", df.columns)
print("\nIndex are:\n", df.index)
print(df.head(2))
print(df.tail(3))
print("\nTranspose of df is :\n", df.describe().transpose())

Columns are:
 Index(['total_bill', 'tip', 'gender', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'Payer Name', 'CC Number', 'Payment ID'],
      dtype='object')

Index are:
 RangeIndex(start=0, stop=244, step=1)
   total_bill   tip  gender smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   

           Payer Name     CC Number Payment ID  
0  Christy Cunningham  3.560330e+15    Sun2959  
1      Douglas Tucker  4.478070e+15    Sun4608  
     total_bill   tip  gender smoker   day    time  size  price_per_person  \
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

          Payer Name     CC Number Payment ID  
241       Keith Wong  6.011890e+15    S

# Column Selection and indexing

In [ ]:
# Selecting a single column
print(df['total_bill'])
print(type(df['total_bill']))

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...  
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64
<class 'pandas.core.series.Series'>


In [ ]:
# Selecting multiple columns ( use a list of column names)
print(df[['total_bill', 'tip']])
print(type(df[['total_bill', 'tip']]))

     total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]
<class 'pandas.core.frame.DataFrame'>


In [ ]:
# Create new columns based on existing ones
df['tip_percentage'] = 100 * df['tip'] / df['total_bill']
df['price_per_person'] = df['total_bill'] / df['size']
print(df.head())

   total_bill   tip  gender smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2          8.495000   
1       10.34  1.66    Male     No  Sun  Dinner     3          3.446667   
2       21.01  3.50    Male     No  Sun  Dinner     3          7.003333   
3       23.68  3.31    Male     No  Sun  Dinner     2         11.840000   
4       24.59  3.61  Female     No  Sun  Dinner     4          6.147500   

           Payer Name     CC Number Payment ID  tip_percentage  
0  Christy Cunningham  3.560330e+15    Sun2959        5.944673  
1      Douglas Tucker  4.478070e+15    Sun4608       16.054159  
2      Travis Walters  6.011810e+15    Sun4458       16.658734  
3    Nathaniel Harris  4.676140e+15    Sun5260       13.978041  
4        Tonya Carter  4.832730e+15    Sun2251       14.680765  


In [ ]:
# Adjust the 'price_per_person' column by rounding it to 2 decimal places
df['price_per_person'] = np.round(df['price_per_person'],2)
print(df.head())

   total_bill   tip  gender smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name     CC Number Payment ID  tip_percentage  
0  Christy Cunningham  3.560330e+15    Sun2959        5.944673  
1      Douglas Tucker  4.478070e+15    Sun4608       16.054159  
2      Travis Walters  6.011810e+15    Sun4458       16.658734  
3    Nathaniel Harris  4.676140e+15    Sun5260       13.978041  
4        Tonya Carter  4.832730e+15    Sun2251       14.680765  


In [ ]:
# Remove the 'tip_percentage' column
df = df.drop('tip_percentage', axis=1)
print(df.head())

   total_bill   tip  gender smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name     CC Number Payment ID  
0  Christy Cunningham  3.560330e+15    Sun2959  
1      Douglas Tucker  4.478070e+15    Sun4608  
2      Travis Walters  6.011810e+15    Sun4458  
3    Nathaniel Harris  4.676140e+15    Sun5260  
4        Tonya Carter  4.832730e+15    Sun2251  


In [ ]:
# Show all columns in the display
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
print(df)

     total_bill    tip  gender smoker   day    time  size  price_per_person  \
0         16.99   1.01  Female     No   Sun  Dinner     2              8.49   
1         10.34   1.66    Male     No   Sun  Dinner     3              3.45   
2         21.01   3.50    Male     No   Sun  Dinner     3              7.00   
3         23.68   3.31    Male     No   Sun  Dinner     2             11.84   
4         24.59   3.61  Female     No   Sun  Dinner     4              6.15   
5         25.29   4.71    Male     No   Sun  Dinner     4              6.32   
6          8.77   2.00    Male     No   Sun  Dinner     2              4.38   
7         26.88   3.12    Male     No   Sun  Dinner     4              6.72   
8         15.04   1.96    Male     No   Sun  Dinner     2              7.52   
9         14.78   3.23    Male     No   Sun  Dinner     2              7.39   
10        10.27   1.71    Male     No   Sun  Dinner     2              5.14   
11        35.26   5.00  Female     No   Sun  Dinner 

In [ ]:
pd.reset_option('display.max_columns')
pd.reset_option('display.max_rows')
print(df)

     total_bill   tip  gender smoker   day    time  size  price_per_person  \
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49   
1         10.34  1.66    Male     No   Sun  Dinner     3              3.45   
2         21.01  3.50    Male     No   Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No   Sun  Dinner     2             11.84   
4         24.59  3.61  Female     No   Sun  Dinner     4              6.15   
..          ...   ...     ...    ...   ...     ...   ...               ...   
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

             Payer Name     CC Number Payment ID  
0    Christy

In [ ]:
# Accessing rows by index
print(df.iloc[0])

total_bill                       16.99
tip                               1.01
gender                          Female
smoker                              No
day                                Sun
time                            Dinner
size                                 2
price_per_person                  8.49
Payer Name          Christy Cunningham
CC Number           3560330000000000.0
Payment ID                     Sun2959
Name: 0, dtype: object


In [ ]:
print(df.loc[0])

total_bill                       16.99
tip                               1.01
gender                          Female
smoker                              No
day                                Sun
time                            Dinner
size                                 2
price_per_person                  8.49
Payer Name          Christy Cunningham
CC Number           3560330000000000.0
Payment ID                     Sun2959
Name: 0, dtype: object
